-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 17:11:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`professor` (
  `cpfProfessor` VARCHAR(45) NOT NULL,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpfProfessor`),
  UNIQUE INDEX `cpfProfessor_UNIQUE` (`cpfProfessor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`aluno` (
  `raAluno` INT NOT NULL,
  `nomeAluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`raAluno`),
  UNIQUE INDEX `raAluno_UNIQUE` (`raAluno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`orientacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`orientacao` (
  `professor_cpfProfessor` VARCHAR(45) NOT NULL,
  `aluno_raAluno` INT NOT NULL,
  `disciplina` VARCHAR(45) NULL,
  PRIMARY KEY (`professor_cpfProfessor`, `aluno_raAluno`),
  INDEX `fk_professor_has_aluno_aluno1_idx` (`aluno_raAluno` ASC) VISIBLE,
  INDEX `fk_professor_has_aluno_professor_idx` (`professor_cpfProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_aluno_professor`
    FOREIGN KEY (`professor_cpfProfessor`)
    REFERENCES `escola`.`professor` (`cpfProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_aluno_aluno1`
    FOREIGN KEY (`aluno_raAluno`)
    REFERENCES `escola`.`aluno` (`raAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
